version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  main:
    build:
      context: .
    ports:
      - '3000:3000'
      - '10022:22'
    restart: always
    volumes:
      - 'resin-data:/data'