version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  main:
    build:
      context: .
    ports:
      - '3000:3000'
      - '10022:22'
    restart: always
    volumes:
      - 'resin-data:/data'

  traefik:
    build: ./balena/traefik
    network_mode: host
    ports:
      - "80:80"
    labels:
      - "io.balena.features.balena-socket=true"
